run_simulation:
	python infection_model.py --params-path /home/cov/git/modelling-ncov2019/test/models/assets/params_experiment0.json --df-individuals-path /home/cov/git/modelling-ncov2019/data/vroclav/population_experiment0.csv --df-households-path /home/cov/git/modelling-ncov2019/data/vroclav/households_experiment0.csv run-simulation
profile:
	python -m cProfile -o profile_experiment0.txt infection_model.py --params-path /home/cov/git/modelling-ncov2019/test/models/assets/params_experiment0.json --df-individuals-path /home/cov/git/modelling-ncov2019/data/vroclav/population_experiment0.csv --df-households-path /home/cov/git/modelling-ncov2019/data/vroclav/households_experiment0.csv run-simulation
